version: '3.3'
services:
  db:
    #image: mysql:8.0.23
    #restart: always
    #environment:
    #  MYSQL_DATABASE: 'db'
    #  # So you don't have to use root, but you can if you like
    #  MYSQL_USER: 'user'
    #  # You can use whatever password you like
    #  MYSQL_PASSWORD: 'password'
    #  # Password for root access
    #  MYSQL_ROOT_PASSWORD: 'password'
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    volumes:
    - ./:/app
    ulimits:
      memlock:
        soft: -1
        hard: -1

      # Where our data will be persisted
    #volumes:
     # - my-db:/var/lib/mysql
# Names our volume
#volumes:
  #my-db:
